config/routes.rb
Blogger::Application.routes.draw do
  resources :users do
    resources :articles do
      resources :comments
    end
  end

  controller :session do
    get "login" => :new
    post "login" => :create
    get "logout" => :destroy
    delete "logout" => :destroy
  end
  
=begin
  match 'articles/:article_id/comments' => "comments#index", :via => :get#, :as => "show_all_article_comments"
  match 'articles/:article_id/comments/:comment_id' => "comments#show", :via => :get, :as => "show_article_comment"
  match 'articles/:article_id/comments/new' => "comments#new", :as => "add_article_comment"
  match 'articles/:article_id/comments/:comment_id/edit' => "comments#edit", :via => :get, :as => "edit_article_comment"
  match 'articles/:article_id/comments/' => "comments#destroy", :via => :delete, :as => "remove_article_comment"
  match 'like/:article_id' => "like#add_like_to_article", :via => :post, :as => "like_article"

=end

  root :to => 'session#new', as: "login"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :datetime, :article_id, :user_id

  validates :content, :presence => true, :length => { :minimum => 1, :maximum => 140 }
  validates :datetime, :presence => true

  belongs_to :article
  belongs_to :user 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :find_article

  # GET /comments
  # GET /comments.json
  def index
    @comments = @article.comments.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = @article.comments.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = @article.comments.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = @article.comments.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create

    @comment = @article.comments.build(params[:comment])
    @comment.user = @user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to user_article_url(@user, @article), notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = @article.comments.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to user_article_comments_url, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = @article.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to user_article_comments_url, notice: 'Comment was successfully destroied' }
      format.json { head :no_content }
    end
  end

protected
  def find_article
      @article = Article.find(params[:article_id])
      @user = @article.user
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_addcomment.erb
<%= form_for([@user, @article, @article.comments.build], :html => {:class => "hero-single-comment"}) do |f| %>
  <table>
        <tr>
          <td><%= image_tag(@user.image_url, :size => "40x40") %></td>
          <td><h3><%= link_to( @user.name + " " + @user.surname, @user, :class => "btn-link") + " " %>says:</h3></td>
        </tr>
  </table>
  <div class="field">
    <%= f.text_area :content, :class => "comment-area", :rows => "3" %>
  </div>
  <p class="numChar">140 characters</p>
  <div class="field datetimeHidden">
    <%= f.datetime_select :datetime %>
  </div>
  <div class="actions">
    <%= f.submit "Comment", :class => "btn btn-primary btn-large" %>
  </div>
  
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@user, @article, @comment])  do |f| %>
  <% if @comment.errors.any? %>
    <div class="alert alert-error">
      <h4>We are sorry but your comment can't be saved cause:</h4>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="hero-single-comment">
    <table>
      <tr>
        <td><%= image_tag(@user.image_url, :size => "40x40") %></td>
        <td><h3><%= link_to( @user.name + " " + @user.surname, @user, :class => "btn-link") + " " %>says:</h3></td>
      </tr>
    </table>
    <div class="field">
      <%= f.text_area :content, :class => "comment-area", :rows => "3" %>
    </div>
    <p class="numChar">140 characters</p>
    <div class="field datetimeHidden">
      <%= f.label :datetime %><br />
      <%= f.datetime_select :datetime %>
    </div>
    <div class="actions">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
  
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= button_to 'Back to comments', user_article_comments_path, method: :get, :class => "btn btn-primary" %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table class="table table-hover table-bordered">
  <tr>
    <th>Content</th>
    <th>Datetime</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @article.comments.each do |comment| %>
  <tr>
    <td><%= raw truncate( comment.content, :length => 200, :omission => (link_to ' ..Continued', user_article_comment_path(@user, @article, comment), :class => "btn-link" ) ) %></td>
    <td><%= comment.datetime %></td>
    <td><%= link_to raw('<i class="icon-home glyph"></i>'), user_article_comment_path(@user, @article, comment), :class => "btn btn-success",:title => "Show" %></td>
    <td><%=  link_to raw('<i class="icon-pencil glyph"></i>'), edit_user_article_comment_path(@user, @article, comment), :class => "btn btn-primary",:title => "Edit" %></td>
    <td><%=  link_to raw('<i class="icon-trash glyph"></i>'), user_article_comment_path(@user, @article, comment), :class => "btn btn-danger", :title => "Detroy", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= button_to 'New Comment', new_user_article_comment_path, method: :get, :class => "btn btn-primary" %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= button_to 'Back to users', user_article_comments_path, method: :get, :class => "btn btn-primary" %>

app/views/comments/show.html.erb
<% if notice%><p class="alert alert-success"><%= notice %></p><% end %>
<% if flash[:error] %><p class="alert alert-error"><%= flash[:error] %></p><% end %>



<div class="hero-single-comment">
	<table>
	  <tr>
	    <td><%= image_tag(@user.image_url, :size => "40x40") %></td>
	    <td><h3><%= link_to( @user.name + " " + @user.surname, @user, :class => "btn-link") + " " %>says:</h3></td>
	  </tr>
	</table>
  	<p><%= @comment.content %></p>
  	<% time = @comment.datetime.strftime("%A %d %B, %Y alle %H:%M") %>
  	<p><%= time_tag(@comment.datetime , time_ago_in_words(@comment.datetime), :title => time ) %> ago</p>
</div>

<%= button_to 'Edit', edit_user_article_comment_path, method: :get, :class => "btn btn-primary" %>
<%= button_to 'Back to comments', user_article_comments_path, method: :get, :class => "btn btn-primary" %>