config/routes.rb
Blogger::Application.routes.draw do
  resources :users do
    resources :articles do
      resources :comments
    end
  end

  controller :session do
    get "login" => :new
    post "login" => :create
    get "logout" => :destroy
    delete "logout" => :destroy
  end
  
=begin
  match 'articles/:article_id/comments' => "comments#index", :via => :get#, :as => "show_all_article_comments"
  match 'articles/:article_id/comments/:comment_id' => "comments#show", :via => :get, :as => "show_article_comment"
  match 'articles/:article_id/comments/new' => "comments#new", :as => "add_article_comment"
  match 'articles/:article_id/comments/:comment_id/edit' => "comments#edit", :via => :get, :as => "edit_article_comment"
  match 'articles/:article_id/comments/' => "comments#destroy", :via => :delete, :as => "remove_article_comment"
  match 'like/:article_id' => "like#add_like_to_article", :via => :post, :as => "like_article"

=end

  root :to => 'session#new', as: "login"

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :content, :datetime, :title, :user_id
  validates :content, :presence => true, :length => { :minimum => 1, :maximum => 15000 }
  belongs_to :user
  has_many :comments
  has_many :likes
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_filter :find_user

  # GET /articles
  # GET /articles.json
  def index
    @articles = @user.articles.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = @user.articles.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = @user.articles.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = @user.articles.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = @user.articles.build(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to user_articles_url(@user), notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = @user.articles.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to user_articles_path(@user) , notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = @user.articles.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to user_articles_url, notice: 'Article was successfully destroied.'  }
      format.json { head :no_content }
    end
  end

  protected
  def find_user
      @user = User.find(params[:user_id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper

	def comment_path(comment)
	  url_for :controller => "comments", :action => "show",
	      :article_id => comment.article, :id => comment
	end
	def edit_comment_path(comment)
	  url_for :controller => "comments", :action => "edit", 
	      :article_id => comment.article, :id => comment
	end
end

app/views/articles/_form.html.erb
<%= form_for([@user, @article])  do |f| %>

  <% if @article.errors.any? %>
    <div class="alert alert-error">
      <h4>We are sorry but this article can't be saved cause:</h4>
      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="hero-unit">
    <%= f.label :title %>
    <%= f.text_field :title %><br/>
    <%= f.label :content %>
    <%= f.text_area :content %><br/>
    <div class="datetimeHidden">
    <%= f.label :datetime %><br />
    <%= f.datetime_select :datetime %>
    </div>
    <div class="actions">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= button_to 'Back to user articles', user_articles_path, method: :get, :class => "btn btn-primary" %>

app/views/articles/index.html.erb
<% if notice%><p class="alert alert-success"><%= notice %></p><% end %>
<% if flash[:error] %><p class="alert alert-error"><%= flash[:error] %></p><% end %>

<h1>Listing <%= @user.name + " " + @user.surname %>'s   articles</h1>

<table class="table table-hover table-bordered">
  <tr>
    <th>Id</th>
    <th>Title</th>
    <th>Content</th>
    <th>Number of comments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.id %></td>
    <td><%= article.title %></td>
    <td><%= raw truncate( article.content, :length => 250, :omission => (link_to ' ..Continued', user_article_path(article.user_id, article), :class => "btn-link" ) ) %></td>
    <td><%= article.comments.count %></td>
    <td><%= link_to raw('<i class="icon-home glyph"></i>'), user_article_path(article.user_id, article), :class => "btn btn-success",:title => "Show" %></td>
    <td><%= link_to raw('<i class="icon-pencil glyph"></i>'), edit_user_article_path(article.user_id, article), :class => "btn btn-primary",:title => "Edit" %></td>
    <td><%= link_to raw('<i class="icon-trash glyph"></i>'), user_article_path(article.user_id, article), :class => "btn btn-danger",:title => "Delete", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= button_to 'New Article', new_user_article_path, method: :get, :class => "btn btn-primary"%>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= button_to 'Back to user articles', user_articles_path, method: :get, :class => "btn btn-primary" %>

app/views/articles/show.html.erb
<% if notice%><p class="alert alert-success"><%= notice %></p><% end %>
<% if flash[:error] %><p class="alert alert-error"><%= flash[:error] %></p><% end %>

<div class="hero-unit">
	<h1><%= @article.title %></h1><br/>
	<p><%= @article.content %></p><br/>
	<p>Written by <%= link_to( @article.user.name + " " + @article.user.surname, @article.user, :class => "btn-link") %>
	<%= time_tag(@article.datetime , time_ago_in_words(@article.datetime), :title => @article.datetime.strftime("%A %d %B, %Y alle %H:%M")) %> ago</p><br/>
	<p><%= pluralize(@article.comments.count, "comment") %>, <%= pluralize(@article.likes.count, "like") %></p>
	<p><%= button_to 'Comment this', new_user_article_comment_path(@article.user_id, @article), method: :get, :class => "btn btn-primary btn-large btn-commentthis" %><%= button_to 'Like this', user_path(@user), :class => "btn btn-primary btn-large btn-likethis" %></p>
	<div style="clear: both;"></div>
</div>

<% @article.comments.each do |comment| %>
    <div class=<%= (comment == @article.comments.first)? "hero-comment-first" : "hero-comment" %>>
    	<table>
    		<tr>
    			<td><%= image_tag(comment.user.image_url, :size => "40x40") %></td>
	    		<td><h3><%= link_to( @article.user.name + " " + @article.user.surname, @article.user, :class => "btn-link") + " " %>says:</h3></td>
	    	</tr>
	    </table><br/>
	    <p>This comment has id <%= comment.id %></p>
	    <p class="commentContent"><%= comment.content %></p>
	    <% time = comment.datetime.strftime("%A %d %B, %Y alle %H:%M") %>
	    <p><%= time_tag(comment.datetime , time_ago_in_words(comment.datetime), :title => time ) %> ago</p>
    </div>
<% end %>

<!-- Add comment form render -->
<%= render "comments/addcomment" %>

<%= button_to 'Edit', edit_user_article_path, method: :get, :class => "btn btn-primary" %>
<%= button_to 'Back to user articles', user_articles_path, method: :get, :class => "btn btn-primary" %>