config/routes.rb
Blogger::Application.routes.draw do
  resources :users do
    resources :articles do
      resources :comments
    end
  end

  controller :session do
    get "login" => :new
    post "login" => :create
    get "logout" => :destroy
    delete "logout" => :destroy
  end
  
=begin
  match 'articles/:article_id/comments' => "comments#index", :via => :get#, :as => "show_all_article_comments"
  match 'articles/:article_id/comments/:comment_id' => "comments#show", :via => :get, :as => "show_article_comment"
  match 'articles/:article_id/comments/new' => "comments#new", :as => "add_article_comment"
  match 'articles/:article_id/comments/:comment_id/edit' => "comments#edit", :via => :get, :as => "edit_article_comment"
  match 'articles/:article_id/comments/' => "comments#destroy", :via => :delete, :as => "remove_article_comment"
  match 'like/:article_id' => "like#add_like_to_article", :via => :post, :as => "like_article"

=end

  root :to => 'session#new', as: "login"

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :image_url, :name, :surname, :id, :created_at, :email, :password_digest, :password, :password_confirmation, :description
  has_secure_password
  has_many :articles
  has_many :comments
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroied.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, :html => {:class => "form-signup form-horizontal"}) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-error">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :name, :placeholder => "Your name" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :surname, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :surname, :placeholder => "Your surname" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :email, :placeholder => "Your email" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => "control-label" %>
    <div class="controls">
      <%= f.password_field :password, :placeholder => "Password" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password_confirmation, "Confirm", :class => "control-label" %>
    <div class="controls">
      <%= f.password_field :password_confirmation, :placeholder => "Confirm" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :image_url, "Your image path", :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :image_url, :placeholder => "Image path" %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "Sign up", :class => "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= button_to 'Back', users_path, method: :get, :class => "btn btn-primary" %>

app/views/users/index.html.erb
<% if notice%><p class="alert alert-success"><%= notice %></p><% end %>
<% if flash[:error] %><p class="alert alert-error"><%= flash[:error] %></p><% end %>

<h1>Listing users</h1>

<table class="table table-hover table-bordered">
  <tr>
    <th></th>
    <th>Name</th>
    <th>Surname</th>
    <th>Email</th>
    <th>Number of articles</th>
    <th>Number of comments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= image_tag user.image_url %></td>
    <td><%= user.name %></td>
    <td><%= user.surname %></td>
    <td><%= user.email %></td>
    <td><%= user.articles.count %></td>
    <td><%= user.comments.count %></td>
    <td><%= link_to raw('<i class="icon-home glyph"></i>'), user, :class => "btn btn-success",:title => "Show" %></td>
    <td><%= link_to raw('<i class="icon-pencil glyph"></i>'), edit_user_path(user), :class => "btn btn-primary",:title => "Edit" %></td>
    <td><%= link_to raw('<i class="icon-trash glyph"></i>'), user, :class => "btn btn-danger",:title => "Destroy", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= button_to 'New User', new_user_path, method: :get, :class => "btn btn-primary btn-large" %>

app/views/users/new.html.erb
<% if notice%><p class="alert alert-success"><%= notice %></p><% end %>
<% if flash[:error] %><p class="alert alert-error"><%= flash[:error] %></p><% end %>

  <h2 class="form-signup-heading">Register</h2>

<%= render 'form' %>

<%= button_to 'Back', users_path, method: :get, :class => "btn btn-primary" %>

app/views/users/show.html.erb
<% if notice%><p class="alert alert-success"><%= notice %></p><% end %>
<% if flash[:error] %><p class="alert alert-error"><%= flash[:error] %></p><% end %>

<!--
<div class="container">
	<div id="cover" class="img-polaroid"><%= image_tag @user.image_url, :size => "200x200" %></div>
	<div id="userNameSurname"><%= @user.name + " " + @user.surname %></div>
</div>
-->

<section id="profile">
	<div style="height: 150px;">
	    <div id="userImageDiv">
	        <%= image_tag @user.image_url, :size => "200x200" %>
	    </div>
	    <div>
		    <h2 id="userInfoGlob"><%= @user.name + " " + @user.surname %></h2>
		    <h5 id="userInfoMail"><i class="icon-envelope" style="vertical-align: middle"></i> <%= @user.email %></h5>
		    <div id="userConfig" class="dropdown">
		      <a data-toggle="dropdown" class="dropdown-toggle btn-link" href="#"><i class="icon-cog" style="vertical-align: middle"></i></a>
		      <ul class="dropdown-menu">
		        <li><%= link_to "Settings", edit_user_path(@user) %></li>
		        <li><a href="#">Another action</a></li>
		        <li><a href="#">Something else here</a></li>
		        <li class="divider"></li>
		        <li><%= link_to "Logout", logout_path %></li>
		      </ul>
		    </div>
		</div>
	</div>
    <p class="lead"><%= @user.description %></p>
    <div>
    <h2>Listing <%= @user.name + " " + @user.surname %>'s   articles</h2>
	<% @user.articles.each do |article| %>
	  <h4><%= link_to article.title, user_article_path(@user, article), :class => "btn-link" %>, <%= pluralize(article.comments.count, "comment") %></h4>
	<% end %>
    </div>
    <br/>
</section>
<br/>

<%= button_to 'Edit', edit_user_path(@user), method: :get, :class => "btn btn-primary" %>
<%= button_to 'Back', users_path, method: :get, :class => "btn btn-primary"%>
<%= button_to 'Write article', new_user_article_path(@user), method: :get, :class => "btn btn-primary"%>